apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlh-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlh
  template:
    metadata:
      labels:
        app: mlh
    spec:
      containers:
        - name: djangopod-container
          image: parth721/django-mlh:8
          resources:
            requests:
              memory: "200Mi"
              cpu: "500m"
            limits:
              memory: "400Mi"
              cpu: "900m"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: sqlite-storage
              mountPath: /usr/src/app/data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
      
