# Generated by Django 4.2.4 on 2023-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=50)),
                ('partner_country', models.CharField(max_length=3)),
                ('partner_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_area', models.CharField(max_length=30)),
                ('partner_city', models.CharField(max_length=30)),
                ('partner_state', models.CharField(max_length=30)),
                ('partner_lon', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('partner_lat', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_country', models.CharField(max_length=3)),
                ('user_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_purpose', models.CharField(max_length=20)),
                ('user_area', models.CharField(max_length=20)),
                ('user_city', models.CharField(max_length=20)),
                ('user_state', models.CharField(max_length=20)),
                ('user_lon', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('user_lat', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
            ],
        ),
    ]
